-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_canny_detector is
port (
    src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    dst_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    dst_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    dst_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    lowthreshold : IN STD_LOGIC_VECTOR (7 downto 0);
    highthreshold : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    src_TVALID : IN STD_LOGIC;
    src_TREADY : OUT STD_LOGIC;
    lowthreshold_ap_vld : IN STD_LOGIC;
    highthreshold_ap_vld : IN STD_LOGIC;
    dst_TVALID : OUT STD_LOGIC;
    dst_TREADY : IN STD_LOGIC );
end;


architecture behav of edge_canny_detector is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "edge_canny_detector_edge_canny_detector,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325t-ffg900-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.180804,HLS_SYN_LAT=4167987,HLS_SYN_TPT=2088860,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=5105,HLS_SYN_LUT=8219,HLS_VERSION=2020_2}";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_start : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_full_n : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_done : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_out : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_rgb_img_src_4206_din : STD_LOGIC_VECTOR (23 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_rgb_img_src_4206_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_src_TREADY : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_lowthreshold_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_lowthreshold_out_write : STD_LOGIC;
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_highthreshold_out_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2xfMat_24_9_1080_1920_1_16_U0_highthreshold_out_write : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_start : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_done : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_continue : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_idle : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_ap_ready : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_start_out : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_start_write : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_rgb_img_src_4206_read : STD_LOGIC;
    signal xfrgb2gray_1080_1920_U0_gray_img_src_4207_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xfrgb2gray_1080_1920_U0_gray_img_src_4207_write : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_start : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_done : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_continue : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_idle : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_ready : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_start_out : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_start_write : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gray_img_src_4207_read : STD_LOGIC;
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gaussian_mat_4209_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gaussian_mat_4209_write : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_start : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_done : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_continue : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_idle : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_ready : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_start_out : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_start_write : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gaussian_mat_4209_read : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gradx_mat_4210_din : STD_LOGIC_VECTOR (15 downto 0);
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gradx_mat_4210_write : STD_LOGIC;
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_grady_mat_4213_din : STD_LOGIC_VECTOR (15 downto 0);
    signal xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_grady_mat_4213_write : STD_LOGIC;
    signal duplicate_1080_1920_U0_ap_start : STD_LOGIC;
    signal duplicate_1080_1920_U0_start_full_n : STD_LOGIC;
    signal duplicate_1080_1920_U0_ap_done : STD_LOGIC;
    signal duplicate_1080_1920_U0_ap_continue : STD_LOGIC;
    signal duplicate_1080_1920_U0_ap_idle : STD_LOGIC;
    signal duplicate_1080_1920_U0_ap_ready : STD_LOGIC;
    signal duplicate_1080_1920_U0_start_out : STD_LOGIC;
    signal duplicate_1080_1920_U0_start_write : STD_LOGIC;
    signal duplicate_1080_1920_U0_gradx_mat_4210_read : STD_LOGIC;
    signal duplicate_1080_1920_U0_grady_mat_4213_read : STD_LOGIC;
    signal duplicate_1080_1920_U0_gradx1_mat_4211_din : STD_LOGIC_VECTOR (15 downto 0);
    signal duplicate_1080_1920_U0_gradx1_mat_4211_write : STD_LOGIC;
    signal duplicate_1080_1920_U0_gradx2_mat_4212_din : STD_LOGIC_VECTOR (15 downto 0);
    signal duplicate_1080_1920_U0_gradx2_mat_4212_write : STD_LOGIC;
    signal duplicate_1080_1920_U0_grady1_mat_4214_din : STD_LOGIC_VECTOR (15 downto 0);
    signal duplicate_1080_1920_U0_grady1_mat_4214_write : STD_LOGIC;
    signal duplicate_1080_1920_U0_grady2_mat_4215_din : STD_LOGIC_VECTOR (15 downto 0);
    signal duplicate_1080_1920_U0_grady2_mat_4215_write : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_start : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_done : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_continue : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_idle : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_ready : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_gradx1_mat_4211_read : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_grady1_mat_4214_read : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_magnitude_mat_4216_din : STD_LOGIC_VECTOR (15 downto 0);
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_magnitude_mat_4216_write : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_start : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_done : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_continue : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_idle : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_ready : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_gradx2_mat_4212_read : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_grady2_mat_4215_read : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_phase_mat_4217_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_phase_mat_4217_write : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_start : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_done : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_continue : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_idle : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_ready : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_start_out : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_start_write : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_magnitude_mat_data_read : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_phase_mat_data_read : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_nms_mat_data_din : STD_LOGIC_VECTOR (7 downto 0);
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_nms_mat_data_write : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_lowthreshold_read : STD_LOGIC;
    signal xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_highthreshold_read : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_start : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_done : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_continue : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_idle : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_ap_ready : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_start_out : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_start_write : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_nms_mat_4218_read : STD_LOGIC;
    signal xfgray2rgb_1080_1920_U0_rgb_img_dst_4208_din : STD_LOGIC_VECTOR (23 downto 0);
    signal xfgray2rgb_1080_1920_U0_rgb_img_dst_4208_write : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_rgb_img_dst_4208_read : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TVALID : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal rgb_img_src_data_full_n : STD_LOGIC;
    signal rgb_img_src_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal rgb_img_src_data_empty_n : STD_LOGIC;
    signal lowthreshold_c_full_n : STD_LOGIC;
    signal lowthreshold_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal lowthreshold_c_empty_n : STD_LOGIC;
    signal highthreshold_c_full_n : STD_LOGIC;
    signal highthreshold_c_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal highthreshold_c_empty_n : STD_LOGIC;
    signal gray_img_src_data_full_n : STD_LOGIC;
    signal gray_img_src_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal gray_img_src_data_empty_n : STD_LOGIC;
    signal gaussian_mat_data_full_n : STD_LOGIC;
    signal gaussian_mat_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal gaussian_mat_data_empty_n : STD_LOGIC;
    signal gradx_mat_data_full_n : STD_LOGIC;
    signal gradx_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal gradx_mat_data_empty_n : STD_LOGIC;
    signal grady_mat_data_full_n : STD_LOGIC;
    signal grady_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal grady_mat_data_empty_n : STD_LOGIC;
    signal gradx1_mat_data_full_n : STD_LOGIC;
    signal gradx1_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal gradx1_mat_data_empty_n : STD_LOGIC;
    signal gradx2_mat_data_full_n : STD_LOGIC;
    signal gradx2_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal gradx2_mat_data_empty_n : STD_LOGIC;
    signal grady1_mat_data_full_n : STD_LOGIC;
    signal grady1_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal grady1_mat_data_empty_n : STD_LOGIC;
    signal grady2_mat_data_full_n : STD_LOGIC;
    signal grady2_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal grady2_mat_data_empty_n : STD_LOGIC;
    signal magnitude_mat_data_full_n : STD_LOGIC;
    signal magnitude_mat_data_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal magnitude_mat_data_empty_n : STD_LOGIC;
    signal phase_mat_data_full_n : STD_LOGIC;
    signal phase_mat_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal phase_mat_data_empty_n : STD_LOGIC;
    signal nms_mat_data_full_n : STD_LOGIC;
    signal nms_mat_data_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal nms_mat_data_empty_n : STD_LOGIC;
    signal rgb_img_dst_data_full_n : STD_LOGIC;
    signal rgb_img_dst_data_dout : STD_LOGIC_VECTOR (23 downto 0);
    signal rgb_img_dst_data_empty_n : STD_LOGIC;
    signal start_for_xfrgb2gray_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfrgb2gray_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_xfrgb2gray_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfrgb2gray_1080_1920_U0_empty_n : STD_LOGIC;
    signal start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_full_n : STD_LOGIC;
    signal start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_empty_n : STD_LOGIC;
    signal start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_full_n : STD_LOGIC;
    signal start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_empty_n : STD_LOGIC;
    signal start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_full_n : STD_LOGIC;
    signal start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_empty_n : STD_LOGIC;
    signal start_for_duplicate_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_duplicate_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_duplicate_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_duplicate_1080_1920_U0_empty_n : STD_LOGIC;
    signal start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_full_n : STD_LOGIC;
    signal start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_empty_n : STD_LOGIC;
    signal start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_full_n : STD_LOGIC;
    signal start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_empty_n : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_start_full_n : STD_LOGIC;
    signal xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_start_write : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_start_full_n : STD_LOGIC;
    signal xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_start_write : STD_LOGIC;
    signal start_for_xfgray2rgb_1080_1920_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfgray2rgb_1080_1920_U0_full_n : STD_LOGIC;
    signal start_for_xfgray2rgb_1080_1920_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfgray2rgb_1080_1920_U0_empty_n : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n : STD_LOGIC;
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_start_full_n : STD_LOGIC;
    signal xfMat2AXIvideo_24_9_1080_1920_1_U0_start_write : STD_LOGIC;

    component edge_canny_detector_AXIvideo2xfMat_24_9_1080_1920_1_16 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        rgb_img_src_4206_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        rgb_img_src_4206_full_n : IN STD_LOGIC;
        rgb_img_src_4206_write : OUT STD_LOGIC;
        src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        src_TVALID : IN STD_LOGIC;
        src_TREADY : OUT STD_LOGIC;
        src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        lowthreshold : IN STD_LOGIC_VECTOR (7 downto 0);
        lowthreshold_ap_vld : IN STD_LOGIC;
        highthreshold : IN STD_LOGIC_VECTOR (7 downto 0);
        highthreshold_ap_vld : IN STD_LOGIC;
        lowthreshold_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        lowthreshold_out_full_n : IN STD_LOGIC;
        lowthreshold_out_write : OUT STD_LOGIC;
        highthreshold_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        highthreshold_out_full_n : IN STD_LOGIC;
        highthreshold_out_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xfrgb2gray_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        rgb_img_src_4206_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        rgb_img_src_4206_empty_n : IN STD_LOGIC;
        rgb_img_src_4206_read : OUT STD_LOGIC;
        gray_img_src_4207_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        gray_img_src_4207_full_n : IN STD_LOGIC;
        gray_img_src_4207_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        gray_img_src_4207_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        gray_img_src_4207_empty_n : IN STD_LOGIC;
        gray_img_src_4207_read : OUT STD_LOGIC;
        gaussian_mat_4209_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        gaussian_mat_4209_full_n : IN STD_LOGIC;
        gaussian_mat_4209_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        gaussian_mat_4209_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        gaussian_mat_4209_empty_n : IN STD_LOGIC;
        gaussian_mat_4209_read : OUT STD_LOGIC;
        gradx_mat_4210_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        gradx_mat_4210_full_n : IN STD_LOGIC;
        gradx_mat_4210_write : OUT STD_LOGIC;
        grady_mat_4213_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        grady_mat_4213_full_n : IN STD_LOGIC;
        grady_mat_4213_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_duplicate_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        gradx_mat_4210_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        gradx_mat_4210_empty_n : IN STD_LOGIC;
        gradx_mat_4210_read : OUT STD_LOGIC;
        grady_mat_4213_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        grady_mat_4213_empty_n : IN STD_LOGIC;
        grady_mat_4213_read : OUT STD_LOGIC;
        gradx1_mat_4211_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        gradx1_mat_4211_full_n : IN STD_LOGIC;
        gradx1_mat_4211_write : OUT STD_LOGIC;
        gradx2_mat_4212_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        gradx2_mat_4212_full_n : IN STD_LOGIC;
        gradx2_mat_4212_write : OUT STD_LOGIC;
        grady1_mat_4214_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        grady1_mat_4214_full_n : IN STD_LOGIC;
        grady1_mat_4214_write : OUT STD_LOGIC;
        grady2_mat_4215_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        grady2_mat_4215_full_n : IN STD_LOGIC;
        grady2_mat_4215_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        gradx1_mat_4211_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        gradx1_mat_4211_empty_n : IN STD_LOGIC;
        gradx1_mat_4211_read : OUT STD_LOGIC;
        grady1_mat_4214_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        grady1_mat_4214_empty_n : IN STD_LOGIC;
        grady1_mat_4214_read : OUT STD_LOGIC;
        magnitude_mat_4216_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        magnitude_mat_4216_full_n : IN STD_LOGIC;
        magnitude_mat_4216_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        gradx2_mat_4212_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        gradx2_mat_4212_empty_n : IN STD_LOGIC;
        gradx2_mat_4212_read : OUT STD_LOGIC;
        grady2_mat_4215_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        grady2_mat_4215_empty_n : IN STD_LOGIC;
        grady2_mat_4215_read : OUT STD_LOGIC;
        phase_mat_4217_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        phase_mat_4217_full_n : IN STD_LOGIC;
        phase_mat_4217_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        magnitude_mat_data_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        magnitude_mat_data_empty_n : IN STD_LOGIC;
        magnitude_mat_data_read : OUT STD_LOGIC;
        phase_mat_data_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        phase_mat_data_empty_n : IN STD_LOGIC;
        phase_mat_data_read : OUT STD_LOGIC;
        nms_mat_data_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        nms_mat_data_full_n : IN STD_LOGIC;
        nms_mat_data_write : OUT STD_LOGIC;
        lowthreshold_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        lowthreshold_empty_n : IN STD_LOGIC;
        lowthreshold_read : OUT STD_LOGIC;
        highthreshold_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        highthreshold_empty_n : IN STD_LOGIC;
        highthreshold_read : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xfgray2rgb_1080_1920_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        nms_mat_4218_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        nms_mat_4218_empty_n : IN STD_LOGIC;
        nms_mat_4218_read : OUT STD_LOGIC;
        rgb_img_dst_4208_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        rgb_img_dst_4208_full_n : IN STD_LOGIC;
        rgb_img_dst_4208_write : OUT STD_LOGIC );
    end component;


    component edge_canny_detector_xfMat2AXIvideo_24_9_1080_1920_1_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rgb_img_dst_4208_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        rgb_img_dst_4208_empty_n : IN STD_LOGIC;
        rgb_img_dst_4208_read : OUT STD_LOGIC;
        dst_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        dst_TVALID : OUT STD_LOGIC;
        dst_TREADY : IN STD_LOGIC;
        dst_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        dst_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        dst_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component edge_canny_detector_fifo_w24_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (23 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (23 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_fifo_w8_d7_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_fifo_w8_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_fifo_w16_d3840_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_fifo_w8_d3840_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xfrgb2gray_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_duplicate_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xfgray2rgb_1080_1920_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component edge_canny_detector_start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    AXIvideo2xfMat_24_9_1080_1920_1_16_U0 : component edge_canny_detector_AXIvideo2xfMat_24_9_1080_1920_1_16
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_start,
        start_full_n => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_full_n,
        ap_done => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_done,
        ap_continue => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_continue,
        ap_idle => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_idle,
        ap_ready => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_ready,
        start_out => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_out,
        start_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_write,
        rgb_img_src_4206_din => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_rgb_img_src_4206_din,
        rgb_img_src_4206_full_n => rgb_img_src_data_full_n,
        rgb_img_src_4206_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_rgb_img_src_4206_write,
        src_TDATA => src_TDATA,
        src_TVALID => src_TVALID,
        src_TREADY => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_src_TREADY,
        src_TKEEP => src_TKEEP,
        src_TSTRB => src_TSTRB,
        src_TUSER => src_TUSER,
        src_TLAST => src_TLAST,
        src_TID => src_TID,
        src_TDEST => src_TDEST,
        lowthreshold => lowthreshold,
        lowthreshold_ap_vld => lowthreshold_ap_vld,
        highthreshold => highthreshold,
        highthreshold_ap_vld => highthreshold_ap_vld,
        lowthreshold_out_din => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_lowthreshold_out_din,
        lowthreshold_out_full_n => lowthreshold_c_full_n,
        lowthreshold_out_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_lowthreshold_out_write,
        highthreshold_out_din => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_highthreshold_out_din,
        highthreshold_out_full_n => highthreshold_c_full_n,
        highthreshold_out_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_highthreshold_out_write);

    xfrgb2gray_1080_1920_U0 : component edge_canny_detector_xfrgb2gray_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfrgb2gray_1080_1920_U0_ap_start,
        start_full_n => start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_full_n,
        ap_done => xfrgb2gray_1080_1920_U0_ap_done,
        ap_continue => xfrgb2gray_1080_1920_U0_ap_continue,
        ap_idle => xfrgb2gray_1080_1920_U0_ap_idle,
        ap_ready => xfrgb2gray_1080_1920_U0_ap_ready,
        start_out => xfrgb2gray_1080_1920_U0_start_out,
        start_write => xfrgb2gray_1080_1920_U0_start_write,
        rgb_img_src_4206_dout => rgb_img_src_data_dout,
        rgb_img_src_4206_empty_n => rgb_img_src_data_empty_n,
        rgb_img_src_4206_read => xfrgb2gray_1080_1920_U0_rgb_img_src_4206_read,
        gray_img_src_4207_din => xfrgb2gray_1080_1920_U0_gray_img_src_4207_din,
        gray_img_src_4207_full_n => gray_img_src_data_full_n,
        gray_img_src_4207_write => xfrgb2gray_1080_1920_U0_gray_img_src_4207_write);

    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0 : component edge_canny_detector_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_start,
        start_full_n => start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_full_n,
        ap_done => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_done,
        ap_continue => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_continue,
        ap_idle => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_idle,
        ap_ready => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_ready,
        start_out => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_start_out,
        start_write => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_start_write,
        gray_img_src_4207_dout => gray_img_src_data_dout,
        gray_img_src_4207_empty_n => gray_img_src_data_empty_n,
        gray_img_src_4207_read => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gray_img_src_4207_read,
        gaussian_mat_4209_din => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gaussian_mat_4209_din,
        gaussian_mat_4209_full_n => gaussian_mat_data_full_n,
        gaussian_mat_4209_write => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gaussian_mat_4209_write);

    xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0 : component edge_canny_detector_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_start,
        start_full_n => start_for_duplicate_1080_1920_U0_full_n,
        ap_done => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_done,
        ap_continue => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_continue,
        ap_idle => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_idle,
        ap_ready => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_ready,
        start_out => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_start_out,
        start_write => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_start_write,
        gaussian_mat_4209_dout => gaussian_mat_data_dout,
        gaussian_mat_4209_empty_n => gaussian_mat_data_empty_n,
        gaussian_mat_4209_read => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gaussian_mat_4209_read,
        gradx_mat_4210_din => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gradx_mat_4210_din,
        gradx_mat_4210_full_n => gradx_mat_data_full_n,
        gradx_mat_4210_write => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gradx_mat_4210_write,
        grady_mat_4213_din => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_grady_mat_4213_din,
        grady_mat_4213_full_n => grady_mat_data_full_n,
        grady_mat_4213_write => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_grady_mat_4213_write);

    duplicate_1080_1920_U0 : component edge_canny_detector_duplicate_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => duplicate_1080_1920_U0_ap_start,
        start_full_n => duplicate_1080_1920_U0_start_full_n,
        ap_done => duplicate_1080_1920_U0_ap_done,
        ap_continue => duplicate_1080_1920_U0_ap_continue,
        ap_idle => duplicate_1080_1920_U0_ap_idle,
        ap_ready => duplicate_1080_1920_U0_ap_ready,
        start_out => duplicate_1080_1920_U0_start_out,
        start_write => duplicate_1080_1920_U0_start_write,
        gradx_mat_4210_dout => gradx_mat_data_dout,
        gradx_mat_4210_empty_n => gradx_mat_data_empty_n,
        gradx_mat_4210_read => duplicate_1080_1920_U0_gradx_mat_4210_read,
        grady_mat_4213_dout => grady_mat_data_dout,
        grady_mat_4213_empty_n => grady_mat_data_empty_n,
        grady_mat_4213_read => duplicate_1080_1920_U0_grady_mat_4213_read,
        gradx1_mat_4211_din => duplicate_1080_1920_U0_gradx1_mat_4211_din,
        gradx1_mat_4211_full_n => gradx1_mat_data_full_n,
        gradx1_mat_4211_write => duplicate_1080_1920_U0_gradx1_mat_4211_write,
        gradx2_mat_4212_din => duplicate_1080_1920_U0_gradx2_mat_4212_din,
        gradx2_mat_4212_full_n => gradx2_mat_data_full_n,
        gradx2_mat_4212_write => duplicate_1080_1920_U0_gradx2_mat_4212_write,
        grady1_mat_4214_din => duplicate_1080_1920_U0_grady1_mat_4214_din,
        grady1_mat_4214_full_n => grady1_mat_data_full_n,
        grady1_mat_4214_write => duplicate_1080_1920_U0_grady1_mat_4214_write,
        grady2_mat_4215_din => duplicate_1080_1920_U0_grady2_mat_4215_din,
        grady2_mat_4215_full_n => grady2_mat_data_full_n,
        grady2_mat_4215_write => duplicate_1080_1920_U0_grady2_mat_4215_write);

    xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0 : component edge_canny_detector_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_start,
        ap_done => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_done,
        ap_continue => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_continue,
        ap_idle => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_idle,
        ap_ready => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_ready,
        gradx1_mat_4211_dout => gradx1_mat_data_dout,
        gradx1_mat_4211_empty_n => gradx1_mat_data_empty_n,
        gradx1_mat_4211_read => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_gradx1_mat_4211_read,
        grady1_mat_4214_dout => grady1_mat_data_dout,
        grady1_mat_4214_empty_n => grady1_mat_data_empty_n,
        grady1_mat_4214_read => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_grady1_mat_4214_read,
        magnitude_mat_4216_din => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_magnitude_mat_4216_din,
        magnitude_mat_4216_full_n => magnitude_mat_data_full_n,
        magnitude_mat_4216_write => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_magnitude_mat_4216_write);

    xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0 : component edge_canny_detector_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_start,
        ap_done => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_done,
        ap_continue => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_continue,
        ap_idle => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_idle,
        ap_ready => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_ready,
        gradx2_mat_4212_dout => gradx2_mat_data_dout,
        gradx2_mat_4212_empty_n => gradx2_mat_data_empty_n,
        gradx2_mat_4212_read => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_gradx2_mat_4212_read,
        grady2_mat_4215_dout => grady2_mat_data_dout,
        grady2_mat_4215_empty_n => grady2_mat_data_empty_n,
        grady2_mat_4215_read => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_grady2_mat_4215_read,
        phase_mat_4217_din => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_phase_mat_4217_din,
        phase_mat_4217_full_n => phase_mat_data_full_n,
        phase_mat_4217_write => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_phase_mat_4217_write);

    xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0 : component edge_canny_detector_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_start,
        start_full_n => start_for_xfgray2rgb_1080_1920_U0_full_n,
        ap_done => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_done,
        ap_continue => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_continue,
        ap_idle => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_idle,
        ap_ready => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_ready,
        start_out => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_start_out,
        start_write => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_start_write,
        magnitude_mat_data_dout => magnitude_mat_data_dout,
        magnitude_mat_data_empty_n => magnitude_mat_data_empty_n,
        magnitude_mat_data_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_magnitude_mat_data_read,
        phase_mat_data_dout => phase_mat_data_dout,
        phase_mat_data_empty_n => phase_mat_data_empty_n,
        phase_mat_data_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_phase_mat_data_read,
        nms_mat_data_din => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_nms_mat_data_din,
        nms_mat_data_full_n => nms_mat_data_full_n,
        nms_mat_data_write => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_nms_mat_data_write,
        lowthreshold_dout => lowthreshold_c_dout,
        lowthreshold_empty_n => lowthreshold_c_empty_n,
        lowthreshold_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_lowthreshold_read,
        highthreshold_dout => highthreshold_c_dout,
        highthreshold_empty_n => highthreshold_c_empty_n,
        highthreshold_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_highthreshold_read);

    xfgray2rgb_1080_1920_U0 : component edge_canny_detector_xfgray2rgb_1080_1920_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfgray2rgb_1080_1920_U0_ap_start,
        start_full_n => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n,
        ap_done => xfgray2rgb_1080_1920_U0_ap_done,
        ap_continue => xfgray2rgb_1080_1920_U0_ap_continue,
        ap_idle => xfgray2rgb_1080_1920_U0_ap_idle,
        ap_ready => xfgray2rgb_1080_1920_U0_ap_ready,
        start_out => xfgray2rgb_1080_1920_U0_start_out,
        start_write => xfgray2rgb_1080_1920_U0_start_write,
        nms_mat_4218_dout => nms_mat_data_dout,
        nms_mat_4218_empty_n => nms_mat_data_empty_n,
        nms_mat_4218_read => xfgray2rgb_1080_1920_U0_nms_mat_4218_read,
        rgb_img_dst_4208_din => xfgray2rgb_1080_1920_U0_rgb_img_dst_4208_din,
        rgb_img_dst_4208_full_n => rgb_img_dst_data_full_n,
        rgb_img_dst_4208_write => xfgray2rgb_1080_1920_U0_rgb_img_dst_4208_write);

    xfMat2AXIvideo_24_9_1080_1920_1_U0 : component edge_canny_detector_xfMat2AXIvideo_24_9_1080_1920_1_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start,
        ap_done => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_done,
        ap_continue => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue,
        ap_idle => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_idle,
        ap_ready => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready,
        rgb_img_dst_4208_dout => rgb_img_dst_data_dout,
        rgb_img_dst_4208_empty_n => rgb_img_dst_data_empty_n,
        rgb_img_dst_4208_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_rgb_img_dst_4208_read,
        dst_TDATA => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TDATA,
        dst_TVALID => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TVALID,
        dst_TREADY => dst_TREADY,
        dst_TKEEP => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TKEEP,
        dst_TSTRB => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TSTRB,
        dst_TUSER => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TUSER,
        dst_TLAST => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TLAST,
        dst_TID => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TID,
        dst_TDEST => xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TDEST);

    rgb_img_src_data_U : component edge_canny_detector_fifo_w24_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_rgb_img_src_4206_din,
        if_full_n => rgb_img_src_data_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_rgb_img_src_4206_write,
        if_dout => rgb_img_src_data_dout,
        if_empty_n => rgb_img_src_data_empty_n,
        if_read => xfrgb2gray_1080_1920_U0_rgb_img_src_4206_read);

    lowthreshold_c_U : component edge_canny_detector_fifo_w8_d7_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_lowthreshold_out_din,
        if_full_n => lowthreshold_c_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_lowthreshold_out_write,
        if_dout => lowthreshold_c_dout,
        if_empty_n => lowthreshold_c_empty_n,
        if_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_lowthreshold_read);

    highthreshold_c_U : component edge_canny_detector_fifo_w8_d7_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_highthreshold_out_din,
        if_full_n => highthreshold_c_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_highthreshold_out_write,
        if_dout => highthreshold_c_dout,
        if_empty_n => highthreshold_c_empty_n,
        if_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_highthreshold_read);

    gray_img_src_data_U : component edge_canny_detector_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xfrgb2gray_1080_1920_U0_gray_img_src_4207_din,
        if_full_n => gray_img_src_data_full_n,
        if_write => xfrgb2gray_1080_1920_U0_gray_img_src_4207_write,
        if_dout => gray_img_src_data_dout,
        if_empty_n => gray_img_src_data_empty_n,
        if_read => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gray_img_src_4207_read);

    gaussian_mat_data_U : component edge_canny_detector_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gaussian_mat_4209_din,
        if_full_n => gaussian_mat_data_full_n,
        if_write => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_gaussian_mat_4209_write,
        if_dout => gaussian_mat_data_dout,
        if_empty_n => gaussian_mat_data_empty_n,
        if_read => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gaussian_mat_4209_read);

    gradx_mat_data_U : component edge_canny_detector_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gradx_mat_4210_din,
        if_full_n => gradx_mat_data_full_n,
        if_write => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_gradx_mat_4210_write,
        if_dout => gradx_mat_data_dout,
        if_empty_n => gradx_mat_data_empty_n,
        if_read => duplicate_1080_1920_U0_gradx_mat_4210_read);

    grady_mat_data_U : component edge_canny_detector_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_grady_mat_4213_din,
        if_full_n => grady_mat_data_full_n,
        if_write => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_grady_mat_4213_write,
        if_dout => grady_mat_data_dout,
        if_empty_n => grady_mat_data_empty_n,
        if_read => duplicate_1080_1920_U0_grady_mat_4213_read);

    gradx1_mat_data_U : component edge_canny_detector_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => duplicate_1080_1920_U0_gradx1_mat_4211_din,
        if_full_n => gradx1_mat_data_full_n,
        if_write => duplicate_1080_1920_U0_gradx1_mat_4211_write,
        if_dout => gradx1_mat_data_dout,
        if_empty_n => gradx1_mat_data_empty_n,
        if_read => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_gradx1_mat_4211_read);

    gradx2_mat_data_U : component edge_canny_detector_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => duplicate_1080_1920_U0_gradx2_mat_4212_din,
        if_full_n => gradx2_mat_data_full_n,
        if_write => duplicate_1080_1920_U0_gradx2_mat_4212_write,
        if_dout => gradx2_mat_data_dout,
        if_empty_n => gradx2_mat_data_empty_n,
        if_read => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_gradx2_mat_4212_read);

    grady1_mat_data_U : component edge_canny_detector_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => duplicate_1080_1920_U0_grady1_mat_4214_din,
        if_full_n => grady1_mat_data_full_n,
        if_write => duplicate_1080_1920_U0_grady1_mat_4214_write,
        if_dout => grady1_mat_data_dout,
        if_empty_n => grady1_mat_data_empty_n,
        if_read => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_grady1_mat_4214_read);

    grady2_mat_data_U : component edge_canny_detector_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => duplicate_1080_1920_U0_grady2_mat_4215_din,
        if_full_n => grady2_mat_data_full_n,
        if_write => duplicate_1080_1920_U0_grady2_mat_4215_write,
        if_dout => grady2_mat_data_dout,
        if_empty_n => grady2_mat_data_empty_n,
        if_read => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_grady2_mat_4215_read);

    magnitude_mat_data_U : component edge_canny_detector_fifo_w16_d3840_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_magnitude_mat_4216_din,
        if_full_n => magnitude_mat_data_full_n,
        if_write => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_magnitude_mat_4216_write,
        if_dout => magnitude_mat_data_dout,
        if_empty_n => magnitude_mat_data_empty_n,
        if_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_magnitude_mat_data_read);

    phase_mat_data_U : component edge_canny_detector_fifo_w8_d3840_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_phase_mat_4217_din,
        if_full_n => phase_mat_data_full_n,
        if_write => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_phase_mat_4217_write,
        if_dout => phase_mat_data_dout,
        if_empty_n => phase_mat_data_empty_n,
        if_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_phase_mat_data_read);

    nms_mat_data_U : component edge_canny_detector_fifo_w8_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_nms_mat_data_din,
        if_full_n => nms_mat_data_full_n,
        if_write => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_nms_mat_data_write,
        if_dout => nms_mat_data_dout,
        if_empty_n => nms_mat_data_empty_n,
        if_read => xfgray2rgb_1080_1920_U0_nms_mat_4218_read);

    rgb_img_dst_data_U : component edge_canny_detector_fifo_w24_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => xfgray2rgb_1080_1920_U0_rgb_img_dst_4208_din,
        if_full_n => rgb_img_dst_data_full_n,
        if_write => xfgray2rgb_1080_1920_U0_rgb_img_dst_4208_write,
        if_dout => rgb_img_dst_data_dout,
        if_empty_n => rgb_img_dst_data_empty_n,
        if_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_rgb_img_dst_4208_read);

    start_for_xfrgb2gray_1080_1920_U0_U : component edge_canny_detector_start_for_xfrgb2gray_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfrgb2gray_1080_1920_U0_din,
        if_full_n => start_for_xfrgb2gray_1080_1920_U0_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_write,
        if_dout => start_for_xfrgb2gray_1080_1920_U0_dout,
        if_empty_n => start_for_xfrgb2gray_1080_1920_U0_empty_n,
        if_read => xfrgb2gray_1080_1920_U0_ap_ready);

    start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_U : component edge_canny_detector_start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_din,
        if_full_n => start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_full_n,
        if_write => AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_write,
        if_dout => start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_dout,
        if_empty_n => start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_empty_n,
        if_read => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_ready);

    start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_U : component edge_canny_detector_start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_din,
        if_full_n => start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_full_n,
        if_write => xfrgb2gray_1080_1920_U0_start_write,
        if_dout => start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_dout,
        if_empty_n => start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_empty_n,
        if_read => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_ready);

    start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_U : component edge_canny_detector_start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_din,
        if_full_n => start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_full_n,
        if_write => xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_start_write,
        if_dout => start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_dout,
        if_empty_n => start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_empty_n,
        if_read => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_ready);

    start_for_duplicate_1080_1920_U0_U : component edge_canny_detector_start_for_duplicate_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_duplicate_1080_1920_U0_din,
        if_full_n => start_for_duplicate_1080_1920_U0_full_n,
        if_write => xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_start_write,
        if_dout => start_for_duplicate_1080_1920_U0_dout,
        if_empty_n => start_for_duplicate_1080_1920_U0_empty_n,
        if_read => duplicate_1080_1920_U0_ap_ready);

    start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_U : component edge_canny_detector_start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_din,
        if_full_n => start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_full_n,
        if_write => duplicate_1080_1920_U0_start_write,
        if_dout => start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_dout,
        if_empty_n => start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_empty_n,
        if_read => xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_ready);

    start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_U : component edge_canny_detector_start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_din,
        if_full_n => start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_full_n,
        if_write => duplicate_1080_1920_U0_start_write,
        if_dout => start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_dout,
        if_empty_n => start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_empty_n,
        if_read => xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_ready);

    start_for_xfgray2rgb_1080_1920_U0_U : component edge_canny_detector_start_for_xfgray2rgb_1080_1920_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfgray2rgb_1080_1920_U0_din,
        if_full_n => start_for_xfgray2rgb_1080_1920_U0_full_n,
        if_write => xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_start_write,
        if_dout => start_for_xfgray2rgb_1080_1920_U0_dout,
        if_empty_n => start_for_xfgray2rgb_1080_1920_U0_empty_n,
        if_read => xfgray2rgb_1080_1920_U0_ap_ready);

    start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_U : component edge_canny_detector_start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din,
        if_full_n => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_full_n,
        if_write => xfgray2rgb_1080_1920_U0_start_write,
        if_dout => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_dout,
        if_empty_n => start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n,
        if_read => xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_ready);




    AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2xfMat_24_9_1080_1920_1_16_U0_ap_start <= ap_const_logic_1;
    AXIvideo2xfMat_24_9_1080_1920_1_16_U0_start_full_n <= (start_for_xfrgb2gray_1080_1920_U0_full_n and start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_full_n);

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_0;
    dst_TDATA <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TDATA;
    dst_TDEST <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TDEST;
    dst_TID <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TID;
    dst_TKEEP <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TKEEP;
    dst_TLAST <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TLAST;
    dst_TSTRB <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TSTRB;
    dst_TUSER <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TUSER;
    dst_TVALID <= xfMat2AXIvideo_24_9_1080_1920_1_U0_dst_TVALID;
    duplicate_1080_1920_U0_ap_continue <= ap_const_logic_1;
    duplicate_1080_1920_U0_ap_start <= start_for_duplicate_1080_1920_U0_empty_n;
    duplicate_1080_1920_U0_start_full_n <= (start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_full_n and start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_full_n);
    src_TREADY <= AXIvideo2xfMat_24_9_1080_1920_1_16_U0_src_TREADY;
    start_for_duplicate_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfgray2rgb_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_xfrgb2gray_1080_1920_U0_din <= (0=>ap_const_logic_1, others=>'-');
    xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_continue <= ap_const_logic_1;
    xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_ap_start <= start_for_xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_empty_n;
    xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_start_full_n <= ap_const_logic_1;
    xFAngleKernel_2_0_1080_1920_3_0_1_5_1_1920_3840_U0_start_write <= ap_const_logic_0;
    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_continue <= ap_const_logic_1;
    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_ap_start <= start_for_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_1_1920_U0_empty_n;
    xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_continue <= ap_const_logic_1;
    xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_ap_start <= start_for_xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_empty_n;
    xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_start_full_n <= ap_const_logic_1;
    xFMagnitudeKernel_2_2_1080_1920_3_3_1_5_5_1920_3840_U0_start_write <= ap_const_logic_0;
    xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_continue <= ap_const_logic_1;
    xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_ap_start <= start_for_xFSobel_0_2_1080_1920_0_3_1_1_5_3_false_U0_empty_n;
    xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_continue <= ap_const_logic_1;
    xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_ap_start <= start_for_xFSuppression3x3_2_0_0_1080_1920_3_0_0_1_5_1_1_1920_3840_3840_U0_empty_n;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_continue <= ap_const_logic_1;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_ap_start <= start_for_xfMat2AXIvideo_24_9_1080_1920_1_U0_empty_n;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_start_full_n <= ap_const_logic_1;
    xfMat2AXIvideo_24_9_1080_1920_1_U0_start_write <= ap_const_logic_0;
    xfgray2rgb_1080_1920_U0_ap_continue <= ap_const_logic_1;
    xfgray2rgb_1080_1920_U0_ap_start <= start_for_xfgray2rgb_1080_1920_U0_empty_n;
    xfrgb2gray_1080_1920_U0_ap_continue <= ap_const_logic_1;
    xfrgb2gray_1080_1920_U0_ap_start <= start_for_xfrgb2gray_1080_1920_U0_empty_n;
end behav;
