-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_canny_detector_AXIvideo2xfMat_24_9_1080_1920_1_16 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    rgb_img_src_4206_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    rgb_img_src_4206_full_n : IN STD_LOGIC;
    rgb_img_src_4206_write : OUT STD_LOGIC;
    src_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    src_TVALID : IN STD_LOGIC;
    src_TREADY : OUT STD_LOGIC;
    src_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    lowthreshold : IN STD_LOGIC_VECTOR (7 downto 0);
    lowthreshold_ap_vld : IN STD_LOGIC;
    highthreshold : IN STD_LOGIC_VECTOR (7 downto 0);
    highthreshold_ap_vld : IN STD_LOGIC;
    lowthreshold_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    lowthreshold_out_full_n : IN STD_LOGIC;
    lowthreshold_out_write : OUT STD_LOGIC;
    highthreshold_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    highthreshold_out_full_n : IN STD_LOGIC;
    highthreshold_out_write : OUT STD_LOGIC );
end;


architecture behav of edge_canny_detector_AXIvideo2xfMat_24_9_1080_1920_1_16 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_438 : STD_LOGIC_VECTOR (10 downto 0) := "10000111000";
    constant ap_const_lv11_780 : STD_LOGIC_VECTOR (10 downto 0) := "11110000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal rgb_img_src_4206_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln132_reg_408 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_phi_mux_start_phi_fu_175_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal icmp_ln132_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln138_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_phi_mux_axi_last_V_9_phi_fu_315_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal lowthreshold_blk_n : STD_LOGIC;
    signal highthreshold_blk_n : STD_LOGIC;
    signal lowthreshold_out_blk_n : STD_LOGIC;
    signal highthreshold_out_blk_n : STD_LOGIC;
    signal j_reg_231 : STD_LOGIC_VECTOR (10 downto 0);
    signal last_reg_242 : STD_LOGIC_VECTOR (0 downto 0);
    signal start_3_reg_254 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_3_reg_265 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_last_V_3_reg_276 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_8_reg_286 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_299 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state8 : BOOLEAN;
    signal i_3_fu_354_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_3_reg_394 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln128_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_3_fu_366_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_predicate_op122_read_state5 : BOOLEAN;
    signal ap_block_state5_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state5 : STD_LOGIC;
    signal axi_last_V_reg_147 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_reg_159 : STD_LOGIC_VECTOR (23 downto 0);
    signal start_reg_171 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i_reg_182 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal start_2_reg_193 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_4_reg_322 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_data_V_2_reg_207 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_last_V_2_reg_218 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_last_phi_fu_246_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_start_3_phi_fu_257_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_axi_data_V_3_phi_fu_268_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_mux_axi_last_V_3_phi_fu_279_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp1_iter0_axi_last_V_8_reg_286 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp1_iter0_p_Val2_s_reg_299 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_last_V_9_reg_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_apdone_blk : STD_LOGIC;
    signal src_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal src_TVALID_int_regslice : STD_LOGIC;
    signal src_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal src_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_AXI_video_strm_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal src_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_AXI_video_strm_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_apdone_blk : STD_LOGIC;
    signal src_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_apdone_blk : STD_LOGIC;
    signal src_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_apdone_blk : STD_LOGIC;
    signal src_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal src_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_condition_180 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component edge_canny_detector_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_AXI_video_strm_V_data_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TDATA,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_data_V_U_ack_in,
        data_out => src_TDATA_int_regslice,
        vld_out => src_TVALID_int_regslice,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_data_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_keep_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TKEEP,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_keep_V_U_ack_in,
        data_out => src_TKEEP_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_keep_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_strb_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TSTRB,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_strb_V_U_ack_in,
        data_out => src_TSTRB_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_strb_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_user_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TUSER,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_user_V_U_ack_in,
        data_out => src_TUSER_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_user_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_user_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_last_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TLAST,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_last_V_U_ack_in,
        data_out => src_TLAST_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_last_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_last_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_id_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TID,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_id_V_U_ack_in,
        data_out => src_TID_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_id_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_id_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_dest_V_U : component edge_canny_detector_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => src_TDEST,
        vld_in => src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_dest_V_U_ack_in,
        data_out => src_TDEST_int_regslice,
        vld_out => regslice_both_AXI_video_strm_V_dest_V_U_vld_out,
        ack_out => src_TREADY_int_regslice,
        apdone_blk => regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state5);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_V_2_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                axi_data_V_2_reg_207 <= axi_data_V_reg_159;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_data_V_2_reg_207 <= axi_data_V_4_reg_322;
            end if; 
        end if;
    end process;

    axi_data_V_3_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                axi_data_V_3_reg_265 <= axi_data_V_2_reg_207;
            elsif (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                axi_data_V_3_reg_265 <= p_Val2_s_reg_299;
            end if; 
        end if;
    end process;

    axi_data_V_4_reg_322_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                axi_data_V_4_reg_322 <= axi_data_V_3_reg_265;
            elsif ((not(((src_TVALID_int_regslice = ap_const_logic_0) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) then 
                axi_data_V_4_reg_322 <= src_TDATA_int_regslice;
            end if; 
        end if;
    end process;

    axi_last_V_2_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                axi_last_V_2_reg_218 <= axi_last_V_reg_147;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_last_V_2_reg_218 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    axi_last_V_3_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                axi_last_V_3_reg_276 <= axi_last_V_2_reg_218;
            elsif (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                axi_last_V_3_reg_276 <= axi_last_V_8_reg_286;
            end if; 
        end if;
    end process;

    axi_last_V_8_reg_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_180)) then
                if (((or_ln138_fu_378_p2 = ap_const_lv1_1) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0))) then 
                    axi_last_V_8_reg_286 <= ap_phi_mux_axi_last_V_3_phi_fu_279_p4;
                elsif (((or_ln138_fu_378_p2 = ap_const_lv1_0) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0))) then 
                    axi_last_V_8_reg_286 <= src_TLAST_int_regslice;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    axi_last_V_8_reg_286 <= ap_phi_reg_pp1_iter0_axi_last_V_8_reg_286;
                end if;
            end if; 
        end if;
    end process;

    axi_last_V_9_reg_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                axi_last_V_9_reg_312 <= last_reg_242;
            elsif ((not(((src_TVALID_int_regslice = ap_const_logic_0) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) then 
                axi_last_V_9_reg_312 <= src_TLAST_int_regslice;
            end if; 
        end if;
    end process;

    i_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_reg_182 <= ap_const_lv11_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                i_reg_182 <= i_3_reg_394;
            end if; 
        end if;
    end process;

    j_reg_231_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                j_reg_231 <= ap_const_lv11_0;
            elsif (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0))) then 
                j_reg_231 <= j_3_fu_366_p2;
            end if; 
        end if;
    end process;

    last_reg_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                last_reg_242 <= ap_const_lv1_0;
            elsif (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                last_reg_242 <= axi_last_V_8_reg_286;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_180)) then
                if (((or_ln138_fu_378_p2 = ap_const_lv1_1) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0))) then 
                    p_Val2_s_reg_299 <= ap_phi_mux_axi_data_V_3_phi_fu_268_p4;
                elsif (((or_ln138_fu_378_p2 = ap_const_lv1_0) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0))) then 
                    p_Val2_s_reg_299 <= src_TDATA_int_regslice;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_Val2_s_reg_299 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_299;
                end if;
            end if; 
        end if;
    end process;

    start_2_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                start_2_reg_193 <= ap_const_lv1_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                start_2_reg_193 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    start_3_reg_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_0))) then 
                start_3_reg_254 <= start_2_reg_193;
            elsif (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                start_3_reg_254 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    start_reg_171_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((highthreshold_out_full_n = ap_const_logic_0) or (lowthreshold_out_full_n = ap_const_logic_0) or (highthreshold_ap_vld = ap_const_logic_0) or (lowthreshold_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                start_reg_171 <= ap_const_lv1_0;
            elsif ((not(((start_reg_171 = ap_const_lv1_0) and (src_TVALID_int_regslice = ap_const_logic_0))) and (start_reg_171 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                start_reg_171 <= src_TUSER_int_regslice;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((start_reg_171 = ap_const_lv1_0) and (src_TVALID_int_regslice = ap_const_logic_0))) and (start_reg_171 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                axi_data_V_reg_159 <= src_TDATA_int_regslice;
                axi_last_V_reg_147 <= src_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_3_reg_394 <= i_3_fu_354_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                icmp_ln132_reg_408 <= icmp_ln132_fu_372_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, lowthreshold_ap_vld, highthreshold_ap_vld, lowthreshold_out_full_n, highthreshold_out_full_n, ap_CS_fsm_state2, ap_phi_mux_start_phi_fu_175_p4, ap_enable_reg_pp1_iter0, icmp_ln132_fu_372_p2, ap_CS_fsm_state8, ap_phi_mux_axi_last_V_9_phi_fu_315_p4, ap_CS_fsm_state4, icmp_ln128_fu_360_p2, ap_block_pp1_stage0_subdone, start_reg_171, axi_last_V_9_reg_312, src_TVALID_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((highthreshold_out_full_n = ap_const_logic_0) or (lowthreshold_out_full_n = ap_const_logic_0) or (highthreshold_ap_vld = ap_const_logic_0) or (lowthreshold_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((start_reg_171 = ap_const_lv1_0) and (src_TVALID_int_regslice = ap_const_logic_0))) and (start_reg_171 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((start_reg_171 = ap_const_lv1_0) and (src_TVALID_int_regslice = ap_const_logic_0))) and (ap_phi_mux_start_phi_fu_175_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln132_fu_372_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (icmp_ln132_fu_372_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if ((not(((src_TVALID_int_regslice = ap_const_logic_0) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif ((not(((src_TVALID_int_regslice = ap_const_logic_0) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (ap_phi_mux_axi_last_V_9_phi_fu_315_p4 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state7 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(7);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(rgb_img_src_4206_full_n, ap_enable_reg_pp1_iter1, icmp_ln132_reg_408, ap_enable_reg_pp1_iter0, ap_predicate_op122_read_state5, src_TVALID_int_regslice)
    begin
                ap_block_pp1_stage0_01001 <= (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (src_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op122_read_state5 = ap_const_boolean_1)) or ((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (rgb_img_src_4206_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(rgb_img_src_4206_full_n, ap_enable_reg_pp1_iter1, icmp_ln132_reg_408, ap_enable_reg_pp1_iter0, ap_predicate_op122_read_state5, src_TVALID_int_regslice)
    begin
                ap_block_pp1_stage0_11001 <= (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (src_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op122_read_state5 = ap_const_boolean_1)) or ((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (rgb_img_src_4206_full_n = ap_const_logic_0)));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(rgb_img_src_4206_full_n, ap_enable_reg_pp1_iter1, icmp_ln132_reg_408, ap_enable_reg_pp1_iter0, ap_predicate_op122_read_state5, src_TVALID_int_regslice)
    begin
                ap_block_pp1_stage0_subdone <= (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (src_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op122_read_state5 = ap_const_boolean_1)) or ((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (rgb_img_src_4206_full_n = ap_const_logic_0)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, lowthreshold_ap_vld, highthreshold_ap_vld, lowthreshold_out_full_n, highthreshold_out_full_n)
    begin
                ap_block_state1 <= ((highthreshold_out_full_n = ap_const_logic_0) or (lowthreshold_out_full_n = ap_const_logic_0) or (highthreshold_ap_vld = ap_const_logic_0) or (lowthreshold_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(start_reg_171, src_TVALID_int_regslice)
    begin
                ap_block_state2 <= ((start_reg_171 = ap_const_lv1_0) and (src_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state5_pp1_stage0_iter0_assign_proc : process(ap_predicate_op122_read_state5, src_TVALID_int_regslice)
    begin
                ap_block_state5_pp1_stage0_iter0 <= ((src_TVALID_int_regslice = ap_const_logic_0) and (ap_predicate_op122_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp1_stage0_iter1_assign_proc : process(rgb_img_src_4206_full_n, icmp_ln132_reg_408)
    begin
                ap_block_state6_pp1_stage0_iter1 <= ((icmp_ln132_reg_408 = ap_const_lv1_0) and (rgb_img_src_4206_full_n = ap_const_logic_0));
    end process;


    ap_block_state8_assign_proc : process(axi_last_V_9_reg_312, src_TVALID_int_regslice)
    begin
                ap_block_state8 <= ((src_TVALID_int_regslice = ap_const_logic_0) and (axi_last_V_9_reg_312 = ap_const_lv1_0));
    end process;


    ap_condition_180_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0_11001)
    begin
                ap_condition_180 <= ((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_condition_pp1_exit_iter0_state5_assign_proc : process(icmp_ln132_fu_372_p2)
    begin
        if ((icmp_ln132_fu_372_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4, icmp_ln128_fu_360_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_axi_data_V_3_phi_fu_268_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_408, axi_data_V_3_reg_265, p_Val2_s_reg_299)
    begin
        if (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_axi_data_V_3_phi_fu_268_p4 <= p_Val2_s_reg_299;
        else 
            ap_phi_mux_axi_data_V_3_phi_fu_268_p4 <= axi_data_V_3_reg_265;
        end if; 
    end process;


    ap_phi_mux_axi_last_V_3_phi_fu_279_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_408, axi_last_V_3_reg_276, axi_last_V_8_reg_286)
    begin
        if (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_axi_last_V_3_phi_fu_279_p4 <= axi_last_V_8_reg_286;
        else 
            ap_phi_mux_axi_last_V_3_phi_fu_279_p4 <= axi_last_V_3_reg_276;
        end if; 
    end process;

    ap_phi_mux_axi_last_V_9_phi_fu_315_p4 <= axi_last_V_9_reg_312;

    ap_phi_mux_last_phi_fu_246_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_408, last_reg_242, axi_last_V_8_reg_286)
    begin
        if (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_last_phi_fu_246_p4 <= axi_last_V_8_reg_286;
        else 
            ap_phi_mux_last_phi_fu_246_p4 <= last_reg_242;
        end if; 
    end process;


    ap_phi_mux_start_3_phi_fu_257_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_408, start_3_reg_254)
    begin
        if (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_start_3_phi_fu_257_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_start_3_phi_fu_257_p4 <= start_3_reg_254;
        end if; 
    end process;

    ap_phi_mux_start_phi_fu_175_p4 <= start_reg_171;
    ap_phi_reg_pp1_iter0_axi_last_V_8_reg_286 <= "X";
    ap_phi_reg_pp1_iter0_p_Val2_s_reg_299 <= "XXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op122_read_state5_assign_proc : process(icmp_ln132_fu_372_p2, or_ln138_fu_378_p2)
    begin
                ap_predicate_op122_read_state5 <= ((or_ln138_fu_378_p2 = ap_const_lv1_0) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;

    highthreshold_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, highthreshold_ap_vld)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            highthreshold_blk_n <= highthreshold_ap_vld;
        else 
            highthreshold_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    highthreshold_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, highthreshold_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            highthreshold_out_blk_n <= highthreshold_out_full_n;
        else 
            highthreshold_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    highthreshold_out_din <= highthreshold;

    highthreshold_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lowthreshold_ap_vld, highthreshold_ap_vld, lowthreshold_out_full_n, highthreshold_out_full_n)
    begin
        if ((not(((highthreshold_out_full_n = ap_const_logic_0) or (lowthreshold_out_full_n = ap_const_logic_0) or (highthreshold_ap_vld = ap_const_logic_0) or (lowthreshold_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            highthreshold_out_write <= ap_const_logic_1;
        else 
            highthreshold_out_write <= ap_const_logic_0;
        end if; 
    end process;

    i_3_fu_354_p2 <= std_logic_vector(unsigned(i_reg_182) + unsigned(ap_const_lv11_1));
    icmp_ln128_fu_360_p2 <= "1" when (i_reg_182 = ap_const_lv11_438) else "0";
    icmp_ln132_fu_372_p2 <= "1" when (j_reg_231 = ap_const_lv11_780) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state4, icmp_ln128_fu_360_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_360_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_3_fu_366_p2 <= std_logic_vector(unsigned(j_reg_231) + unsigned(ap_const_lv11_1));

    lowthreshold_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lowthreshold_ap_vld)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lowthreshold_blk_n <= lowthreshold_ap_vld;
        else 
            lowthreshold_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lowthreshold_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lowthreshold_out_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lowthreshold_out_blk_n <= lowthreshold_out_full_n;
        else 
            lowthreshold_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lowthreshold_out_din <= lowthreshold;

    lowthreshold_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, lowthreshold_ap_vld, highthreshold_ap_vld, lowthreshold_out_full_n, highthreshold_out_full_n)
    begin
        if ((not(((highthreshold_out_full_n = ap_const_logic_0) or (lowthreshold_out_full_n = ap_const_logic_0) or (highthreshold_ap_vld = ap_const_logic_0) or (lowthreshold_ap_vld = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            lowthreshold_out_write <= ap_const_logic_1;
        else 
            lowthreshold_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln138_fu_378_p2 <= (ap_phi_mux_start_3_phi_fu_257_p4 or ap_phi_mux_last_phi_fu_246_p4);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    rgb_img_src_4206_blk_n_assign_proc : process(rgb_img_src_4206_full_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln132_reg_408)
    begin
        if (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            rgb_img_src_4206_blk_n <= rgb_img_src_4206_full_n;
        else 
            rgb_img_src_4206_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    rgb_img_src_4206_din <= p_Val2_s_reg_299;

    rgb_img_src_4206_write_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln132_reg_408, ap_block_pp1_stage0_11001)
    begin
        if (((icmp_ln132_reg_408 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            rgb_img_src_4206_write <= ap_const_logic_1;
        else 
            rgb_img_src_4206_write <= ap_const_logic_0;
        end if; 
    end process;


    src_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, icmp_ln132_fu_372_p2, or_ln138_fu_378_p2, ap_CS_fsm_state8, start_reg_171, axi_last_V_9_reg_312, src_TVALID_int_regslice)
    begin
        if ((((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (or_ln138_fu_378_p2 = ap_const_lv1_0) and (icmp_ln132_fu_372_p2 = ap_const_lv1_0)) or ((start_reg_171 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (axi_last_V_9_reg_312 = ap_const_lv1_0)))) then 
            src_TDATA_blk_n <= src_TVALID_int_regslice;
        else 
            src_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    src_TREADY <= regslice_both_AXI_video_strm_V_data_V_U_ack_in;

    src_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, ap_CS_fsm_state8, ap_predicate_op122_read_state5, ap_block_pp1_stage0_11001, start_reg_171, axi_last_V_9_reg_312, src_TVALID_int_regslice)
    begin
        if ((((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_predicate_op122_read_state5 = ap_const_boolean_1)) or (not(((src_TVALID_int_regslice = ap_const_logic_0) and (axi_last_V_9_reg_312 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (axi_last_V_9_reg_312 = ap_const_lv1_0)) or (not(((start_reg_171 = ap_const_lv1_0) and (src_TVALID_int_regslice = ap_const_logic_0))) and (start_reg_171 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            src_TREADY_int_regslice <= ap_const_logic_1;
        else 
            src_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
