-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_canny_detector_duplicate_720_1280_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    gradx_mat_4210_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    gradx_mat_4210_empty_n : IN STD_LOGIC;
    gradx_mat_4210_read : OUT STD_LOGIC;
    grady_mat_4213_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    grady_mat_4213_empty_n : IN STD_LOGIC;
    grady_mat_4213_read : OUT STD_LOGIC;
    gradx1_mat_4211_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    gradx1_mat_4211_full_n : IN STD_LOGIC;
    gradx1_mat_4211_write : OUT STD_LOGIC;
    gradx2_mat_4212_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    gradx2_mat_4212_full_n : IN STD_LOGIC;
    gradx2_mat_4212_write : OUT STD_LOGIC;
    grady1_mat_4214_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    grady1_mat_4214_full_n : IN STD_LOGIC;
    grady1_mat_4214_write : OUT STD_LOGIC;
    grady2_mat_4215_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    grady2_mat_4215_full_n : IN STD_LOGIC;
    grady2_mat_4215_write : OUT STD_LOGIC );
end;


architecture behav of edge_canny_detector_duplicate_720_1280_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv20_1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_const_lv20_E1000 : STD_LOGIC_VECTOR (19 downto 0) := "11100001000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal gradx_mat_4210_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln116_reg_116 : STD_LOGIC_VECTOR (0 downto 0);
    signal grady_mat_4213_blk_n : STD_LOGIC;
    signal gradx1_mat_4211_blk_n : STD_LOGIC;
    signal gradx2_mat_4212_blk_n : STD_LOGIC;
    signal grady1_mat_4214_blk_n : STD_LOGIC;
    signal grady2_mat_4215_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_88 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln116_fu_99_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln116_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln116_fu_105_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_88 <= add_ln116_fu_99_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_88 <= ap_const_lv20_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln116_reg_116 <= icmp_ln116_fu_105_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln116_fu_105_p2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln116_fu_105_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln116_fu_105_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln116_fu_99_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_88) + unsigned(ap_const_lv20_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(gradx_mat_4210_empty_n, grady_mat_4213_empty_n, gradx1_mat_4211_full_n, gradx2_mat_4212_full_n, grady1_mat_4214_full_n, grady2_mat_4215_full_n, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx1_mat_4211_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady_mat_4213_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx_mat_4210_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady2_mat_4215_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady1_mat_4214_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx2_mat_4212_full_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(gradx_mat_4210_empty_n, grady_mat_4213_empty_n, gradx1_mat_4211_full_n, gradx2_mat_4212_full_n, grady1_mat_4214_full_n, grady2_mat_4215_full_n, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx1_mat_4211_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady_mat_4213_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx_mat_4210_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady2_mat_4215_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady1_mat_4214_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx2_mat_4212_full_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(gradx_mat_4210_empty_n, grady_mat_4213_empty_n, gradx1_mat_4211_full_n, gradx2_mat_4212_full_n, grady1_mat_4214_full_n, grady2_mat_4215_full_n, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx1_mat_4211_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady_mat_4213_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx_mat_4210_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady2_mat_4215_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady1_mat_4214_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx2_mat_4212_full_n = ap_const_logic_0))));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(gradx_mat_4210_empty_n, grady_mat_4213_empty_n, gradx1_mat_4211_full_n, gradx2_mat_4212_full_n, grady1_mat_4214_full_n, grady2_mat_4215_full_n, icmp_ln116_reg_116)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx1_mat_4211_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady_mat_4213_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx_mat_4210_empty_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady2_mat_4215_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (grady1_mat_4214_full_n = ap_const_logic_0)) or ((icmp_ln116_reg_116 = ap_const_lv1_0) and (gradx2_mat_4212_full_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln116_fu_105_p2)
    begin
        if ((icmp_ln116_fu_105_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    gradx1_mat_4211_blk_n_assign_proc : process(gradx1_mat_4211_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln116_reg_116)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gradx1_mat_4211_blk_n <= gradx1_mat_4211_full_n;
        else 
            gradx1_mat_4211_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    gradx1_mat_4211_din <= gradx_mat_4210_dout;

    gradx1_mat_4211_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gradx1_mat_4211_write <= ap_const_logic_1;
        else 
            gradx1_mat_4211_write <= ap_const_logic_0;
        end if; 
    end process;


    gradx2_mat_4212_blk_n_assign_proc : process(gradx2_mat_4212_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln116_reg_116)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gradx2_mat_4212_blk_n <= gradx2_mat_4212_full_n;
        else 
            gradx2_mat_4212_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    gradx2_mat_4212_din <= gradx_mat_4210_dout;

    gradx2_mat_4212_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gradx2_mat_4212_write <= ap_const_logic_1;
        else 
            gradx2_mat_4212_write <= ap_const_logic_0;
        end if; 
    end process;


    gradx_mat_4210_blk_n_assign_proc : process(gradx_mat_4210_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln116_reg_116)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gradx_mat_4210_blk_n <= gradx_mat_4210_empty_n;
        else 
            gradx_mat_4210_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    gradx_mat_4210_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            gradx_mat_4210_read <= ap_const_logic_1;
        else 
            gradx_mat_4210_read <= ap_const_logic_0;
        end if; 
    end process;


    grady1_mat_4214_blk_n_assign_proc : process(grady1_mat_4214_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln116_reg_116)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grady1_mat_4214_blk_n <= grady1_mat_4214_full_n;
        else 
            grady1_mat_4214_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    grady1_mat_4214_din <= grady_mat_4213_dout;

    grady1_mat_4214_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grady1_mat_4214_write <= ap_const_logic_1;
        else 
            grady1_mat_4214_write <= ap_const_logic_0;
        end if; 
    end process;


    grady2_mat_4215_blk_n_assign_proc : process(grady2_mat_4215_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln116_reg_116)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grady2_mat_4215_blk_n <= grady2_mat_4215_full_n;
        else 
            grady2_mat_4215_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    grady2_mat_4215_din <= grady_mat_4213_dout;

    grady2_mat_4215_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grady2_mat_4215_write <= ap_const_logic_1;
        else 
            grady2_mat_4215_write <= ap_const_logic_0;
        end if; 
    end process;


    grady_mat_4213_blk_n_assign_proc : process(grady_mat_4213_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln116_reg_116)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grady_mat_4213_blk_n <= grady_mat_4213_empty_n;
        else 
            grady_mat_4213_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    grady_mat_4213_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln116_reg_116, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln116_reg_116 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grady_mat_4213_read <= ap_const_logic_1;
        else 
            grady_mat_4213_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln116_fu_105_p2 <= "1" when (indvar_flatten_reg_88 = ap_const_lv20_E1000) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
