-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity edge_canny_detector_xFAverageGaussianMask3x3_0_0_720_1280_0_1_1_1280_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    gray_img_src_4207_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    gray_img_src_4207_empty_n : IN STD_LOGIC;
    gray_img_src_4207_read : OUT STD_LOGIC;
    gaussian_mat_4209_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    gaussian_mat_4209_full_n : IN STD_LOGIC;
    gaussian_mat_4209_write : OUT STD_LOGIC );
end;


architecture behav of edge_canny_detector_xFAverageGaussianMask3x3_0_0_720_1280_0_1_1_1280_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv13_2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_500 : STD_LOGIC_VECTOR (10 downto 0) := "10100000000";
    constant ap_const_lv10_2D1 : STD_LOGIC_VECTOR (9 downto 0) := "1011010001";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv10_2D0 : STD_LOGIC_VECTOR (9 downto 0) := "1011010000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv13_3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000011";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal gray_img_src_4207_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln878_reg_844 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln878_7_reg_890 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i_i338_i_reg_881 : STD_LOGIC_VECTOR (0 downto 0);
    signal gaussian_mat_4209_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp1_iter4 : STD_LOGIC := '0';
    signal icmp_ln870_9_reg_918 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln870_9_reg_918_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal col_V_reg_241 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_V_10_reg_276 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_V_10_reg_276_pp1_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state6_pp1_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op89_read_state7 : BOOLEAN;
    signal ap_block_state7_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_state8_pp1_stage0_iter2 : BOOLEAN;
    signal ap_block_state9_pp1_stage0_iter3 : BOOLEAN;
    signal ap_block_state10_pp1_stage0_iter4 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal b1_V_reg_288 : STD_LOGIC_VECTOR (7 downto 0);
    signal b0_V_reg_300 : STD_LOGIC_VECTOR (7 downto 0);
    signal m1_V_reg_313 : STD_LOGIC_VECTOR (7 downto 0);
    signal m0_V_reg_325 : STD_LOGIC_VECTOR (7 downto 0);
    signal t1_V_reg_338 : STD_LOGIC_VECTOR (7 downto 0);
    signal t0_V_reg_350 : STD_LOGIC_VECTOR (7 downto 0);
    signal A2_reg_363 : STD_LOGIC_VECTOR (9 downto 0);
    signal col_V_9_fu_411_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln878_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln534_fu_423_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln534_reg_848 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln209_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal cmp_i_i338_i_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_V_11_fu_515_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_V_11_reg_885 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal icmp_ln878_7_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_7_reg_890_pp1_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_7_reg_890_pp1_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln878_7_reg_890_pp1_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal bottom_load_2_reg_894 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln870_9_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf1_V_2_reg_922 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp1_iter3 : STD_LOGIC := '0';
    signal src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf2_V_2_reg_927 : STD_LOGIC_VECTOR (7 downto 0);
    signal b2_V_xfExtractPixels_1_1_0_s_fu_396_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal b2_V_reg_932 : STD_LOGIC_VECTOR (7 downto 0);
    signal A0_1_fu_620_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal A0_1_reg_937 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln50_3_fu_658_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln50_3_reg_942 : STD_LOGIC_VECTOR (9 downto 0);
    signal phitmp1_fu_664_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal phitmp1_reg_947 : STD_LOGIC_VECTOR (9 downto 0);
    signal row_V_3_fu_725_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal row_V_3_reg_952 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal g_x_V_6_reg_957 : STD_LOGIC_VECTOR (7 downto 0);
    signal row_ind_V_4_fu_831_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_4_reg_962 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp1_iter2 : STD_LOGIC := '0';
    signal ap_condition_pp1_exit_iter3_state9 : STD_LOGIC;
    signal buf_V_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal buf_V_0_ce0 : STD_LOGIC;
    signal buf_V_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal buf_V_0_ce1 : STD_LOGIC;
    signal buf_V_0_we1 : STD_LOGIC;
    signal buf_V_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal buf_V_1_ce0 : STD_LOGIC;
    signal buf_V_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal buf_V_1_ce1 : STD_LOGIC;
    signal buf_V_1_we1 : STD_LOGIC;
    signal buf_V_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal buf_V_2_ce0 : STD_LOGIC;
    signal buf_V_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_V_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal buf_V_2_ce1 : STD_LOGIC;
    signal buf_V_2_we1 : STD_LOGIC;
    signal buf_V_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386_ap_ready : STD_LOGIC;
    signal src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_ready : STD_LOGIC;
    signal b2_V_xfExtractPixels_1_1_0_s_fu_396_ap_ready : STD_LOGIC;
    signal row_V_reg_252 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_phi_mux_row_ind_V_phi_fu_268_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal row_ind_V_reg_264 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_mux_col_V_10_phi_fu_280_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_b1_V_phi_fu_292_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_b0_V_phi_fu_304_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_m0_V_phi_fu_329_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_t1_V_phi_fu_342_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_t0_V_phi_fu_354_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp1_iter0_buf2_V_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp1_iter1_buf2_V_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp1_iter2_buf2_V_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp1_iter3_buf2_V_reg_375 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf0_V_fu_554_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf1_V_fu_567_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln534_6_fu_527_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln534_5_fu_534_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln117_fu_541_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tp_fu_106 : STD_LOGIC_VECTOR (1 downto 0);
    signal tp_1_fu_470_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal mid_fu_110 : STD_LOGIC_VECTOR (1 downto 0);
    signal mid_2_fu_478_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal bottom_fu_114 : STD_LOGIC_VECTOR (1 downto 0);
    signal bottom_2_fu_486_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal icmp_ln870_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln45_fu_580_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln46_fu_588_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal A00_fu_600_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln45_1_fu_584_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1460_1_fu_592_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln49_fu_610_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln49_fu_616_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln46_1_fu_606_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln48_fu_630_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln47_fu_626_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln48_fu_638_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln48_1_fu_634_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1460_2_fu_596_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln50_2_fu_648_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln50_4_fu_654_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln50_3_fu_644_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal A1_1_fu_672_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal A2_1_fu_679_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln52_6_fu_694_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln52_4_fu_687_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln52_2_fu_698_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln52_7_fu_704_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln52_5_fu_690_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln52_3_fu_708_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1460_fu_739_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln878_1_fu_735_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln50_fu_749_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln878_fu_731_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln50_fu_757_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln50_2_fu_763_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln50_1_fu_753_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln50_1_fu_767_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal A0_fu_743_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal A1_fu_773_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln52_2_fu_789_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln52_fu_781_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln52_fu_793_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln52_3_fu_799_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln52_1_fu_785_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln52_1_fu_803_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal row_ind_V_3_fu_819_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln870_8_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_condition_176 : BOOLEAN;
    signal ap_condition_188 : BOOLEAN;
    signal ap_condition_732 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component edge_canny_detector_xfExtractPixels_1_1_0_s IS
    port (
        ap_ready : OUT STD_LOGIC;
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component edge_canny_detector_mux_32_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component edge_canny_detector_xFAverageGaussianMask3x3_0_0_720_1280_0_1_1_1280_s_buf_V_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    buf_V_0_U : component edge_canny_detector_xFAverageGaussianMask3x3_0_0_720_1280_0_1_1_1280_s_buf_V_0
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_V_0_address0,
        ce0 => buf_V_0_ce0,
        q0 => buf_V_0_q0,
        address1 => buf_V_0_address1,
        ce1 => buf_V_0_ce1,
        we1 => buf_V_0_we1,
        d1 => buf_V_0_d1);

    buf_V_1_U : component edge_canny_detector_xFAverageGaussianMask3x3_0_0_720_1280_0_1_1_1280_s_buf_V_0
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_V_1_address0,
        ce0 => buf_V_1_ce0,
        q0 => buf_V_1_q0,
        address1 => buf_V_1_address1,
        ce1 => buf_V_1_ce1,
        we1 => buf_V_1_we1,
        d1 => buf_V_1_d1);

    buf_V_2_U : component edge_canny_detector_xFAverageGaussianMask3x3_0_0_720_1280_0_1_1_1280_s_buf_V_0
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_V_2_address0,
        ce0 => buf_V_2_ce0,
        q0 => buf_V_2_q0,
        address1 => buf_V_2_address1,
        ce1 => buf_V_2_ce1,
        we1 => buf_V_2_we1,
        d1 => buf_V_2_d1);

    src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386 : component edge_canny_detector_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386_ap_ready,
        p_read1 => buf0_V_fu_554_p5,
        ap_return => src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386_ap_return);

    src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391 : component edge_canny_detector_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_ready,
        p_read1 => buf1_V_fu_567_p5,
        ap_return => src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_return);

    b2_V_xfExtractPixels_1_1_0_s_fu_396 : component edge_canny_detector_xfExtractPixels_1_1_0_s
    port map (
        ap_ready => b2_V_xfExtractPixels_1_1_0_s_fu_396_ap_ready,
        p_read1 => ap_phi_reg_pp1_iter3_buf2_V_reg_375,
        ap_return => b2_V_xfExtractPixels_1_1_0_s_fu_396_ap_return);

    mux_32_8_1_1_U30 : component edge_canny_detector_mux_32_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_0_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => tp_fu_106,
        dout => buf0_V_fu_554_p5);

    mux_32_8_1_1_U31 : component edge_canny_detector_mux_32_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => buf_V_0_q0,
        din1 => buf_V_1_q0,
        din2 => buf_V_2_q0,
        din3 => mid_fu_110,
        dout => buf1_V_fu_567_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp1_flush_enable)) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
                elsif ((((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter3_state9)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0)))) then 
                    ap_enable_reg_pp1_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter3_state9))) then 
                    ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter2;
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    A2_reg_363_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                                A2_reg_363(9 downto 2) <= phitmp1_reg_947(9 downto 2);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                A2_reg_363(2) <= '0';
                A2_reg_363(3) <= '0';
                A2_reg_363(4) <= '0';
                A2_reg_363(5) <= '0';
                A2_reg_363(6) <= '0';
                A2_reg_363(7) <= '0';
                A2_reg_363(8) <= '0';
                A2_reg_363(9) <= '0';
            end if; 
        end if;
    end process;

    ap_phi_reg_pp1_iter1_buf2_V_reg_375_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_176)) then
                if (((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_fu_521_p2 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter1_buf2_V_reg_375 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp1_iter1_buf2_V_reg_375 <= ap_phi_reg_pp1_iter0_buf2_V_reg_375;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp1_iter2_buf2_V_reg_375_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_188)) then
                if (((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp1_iter2_buf2_V_reg_375 <= gray_img_src_4207_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp1_iter2_buf2_V_reg_375 <= ap_phi_reg_pp1_iter1_buf2_V_reg_375;
                end if;
            end if; 
        end if;
    end process;

    b0_V_reg_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                b0_V_reg_300 <= b1_V_reg_288;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                b0_V_reg_300 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    b1_V_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                b1_V_reg_288 <= b2_V_reg_932;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                b1_V_reg_288 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    bottom_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then
                if ((not((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_2)) and not((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_0)))) then 
                    bottom_fu_114 <= bottom_2_fu_486_p3;
                elsif ((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_2)) then 
                    bottom_fu_114 <= ap_const_lv2_2;
                elsif ((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_0)) then 
                    bottom_fu_114 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    col_V_10_reg_276_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                col_V_10_reg_276 <= col_V_11_reg_885;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                col_V_10_reg_276 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    col_V_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_fu_417_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                col_V_reg_241 <= col_V_9_fu_411_p2;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                col_V_reg_241 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    m0_V_reg_325_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                m0_V_reg_325 <= m1_V_reg_313;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                m0_V_reg_325 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    m1_V_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                m1_V_reg_313 <= src_buf2_V_2_reg_927;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                m1_V_reg_313 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    mid_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then
                if ((not((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_2)) and not((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_0)))) then 
                    mid_fu_110 <= mid_2_fu_478_p3;
                elsif ((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_2)) then 
                    mid_fu_110 <= ap_const_lv2_1;
                elsif ((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_0)) then 
                    mid_fu_110 <= ap_const_lv2_2;
                end if;
            end if; 
        end if;
    end process;

    row_V_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                row_V_reg_252 <= ap_const_lv10_1;
            elsif (((gaussian_mat_4209_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                row_V_reg_252 <= row_V_3_reg_952;
            end if; 
        end if;
    end process;

    row_ind_V_reg_264_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                row_ind_V_reg_264 <= ap_const_lv13_2;
            elsif (((gaussian_mat_4209_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                row_ind_V_reg_264 <= row_ind_V_4_reg_962;
            end if; 
        end if;
    end process;

    t0_V_reg_350_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                t0_V_reg_350 <= t1_V_reg_338;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                t0_V_reg_350 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    t1_V_reg_338_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
                t1_V_reg_338 <= src_buf1_V_2_reg_922;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then 
                t1_V_reg_338 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    tp_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then
                if ((not((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_2)) and not((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_0)))) then 
                    tp_fu_106 <= tp_1_fu_470_p3;
                elsif ((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_2)) then 
                    tp_fu_106 <= ap_const_lv2_0;
                elsif ((ap_phi_mux_row_ind_V_phi_fu_268_p4 = ap_const_lv13_0)) then 
                    tp_fu_106 <= ap_const_lv2_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter2_reg = ap_const_lv1_0))) then
                A0_1_reg_937 <= A0_1_fu_620_p2;
                add_ln50_3_reg_942 <= add_ln50_3_fu_658_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp1_iter3_buf2_V_reg_375 <= ap_phi_reg_pp1_iter2_buf2_V_reg_375;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter3 = ap_const_logic_1) and (icmp_ln878_7_reg_890_pp1_iter2_reg = ap_const_lv1_0))) then
                b2_V_reg_932 <= b2_V_xfExtractPixels_1_1_0_s_fu_396_ap_return;
                    phitmp1_reg_947(9 downto 2) <= phitmp1_fu_664_p3(9 downto 2);
                src_buf1_V_2_reg_922 <= src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386_ap_return;
                src_buf2_V_2_reg_927 <= src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln878_7_fu_521_p2 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                bottom_load_2_reg_894 <= bottom_fu_114;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_0))) then
                cmp_i_i338_i_reg_881 <= cmp_i_i338_i_fu_509_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                col_V_10_reg_276_pp1_iter1_reg <= col_V_10_reg_276;
                icmp_ln878_7_reg_890 <= icmp_ln878_7_fu_521_p2;
                icmp_ln878_7_reg_890_pp1_iter1_reg <= icmp_ln878_7_reg_890;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1))) then
                col_V_11_reg_885 <= col_V_11_fu_515_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                g_x_V_6_reg_957 <= add_ln52_1_fu_803_p2(11 downto 4);
                row_V_3_reg_952 <= row_V_3_fu_725_p2;
                row_ind_V_4_reg_962 <= row_ind_V_4_fu_831_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln878_7_reg_890_pp1_iter1_reg = ap_const_lv1_0))) then
                icmp_ln870_9_reg_918 <= icmp_ln870_9_fu_548_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp1_stage0_11001)) then
                icmp_ln870_9_reg_918_pp1_iter3_reg <= icmp_ln870_9_reg_918;
                icmp_ln878_7_reg_890_pp1_iter2_reg <= icmp_ln878_7_reg_890_pp1_iter1_reg;
                icmp_ln878_7_reg_890_pp1_iter3_reg <= icmp_ln878_7_reg_890_pp1_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln878_reg_844 <= icmp_ln878_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_fu_417_p2 = ap_const_lv1_0))) then
                    zext_ln534_reg_848(10 downto 0) <= zext_ln534_fu_423_p1(10 downto 0);
            end if;
        end if;
    end process;
    A2_reg_363(1 downto 0) <= "00";
    zext_ln534_reg_848(63 downto 11) <= "00000000000000000000000000000000000000000000000000000";
    phitmp1_reg_947(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, gaussian_mat_4209_full_n, ap_CS_fsm_state12, ap_enable_reg_pp0_iter0, icmp_ln878_fu_417_p2, icmp_ln209_fu_428_p2, ap_CS_fsm_state5, ap_enable_reg_pp1_iter3, ap_block_pp0_stage0_subdone, ap_block_pp1_stage0_subdone, ap_enable_reg_pp1_iter2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln878_fu_417_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln878_fu_417_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((gaussian_mat_4209_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    A00_fu_600_p2 <= std_logic_vector(unsigned(zext_ln45_fu_580_p1) + unsigned(zext_ln46_fu_588_p1));
    A0_1_fu_620_p2 <= std_logic_vector(unsigned(zext_ln49_fu_616_p1) + unsigned(zext_ln46_1_fu_606_p1));
    A0_fu_743_p2 <= std_logic_vector(unsigned(zext_ln1460_fu_739_p1) + unsigned(zext_ln878_1_fu_735_p1));
    A1_1_fu_672_p3 <= (add_ln50_3_reg_942 & ap_const_lv1_0);
    A1_fu_773_p3 <= (add_ln50_1_fu_767_p2 & ap_const_lv1_0);
    A2_1_fu_679_p3 <= (m1_V_reg_313 & ap_const_lv2_0);
    add_ln48_fu_638_p2 <= std_logic_vector(unsigned(zext_ln48_fu_630_p1) + unsigned(zext_ln47_fu_626_p1));
    add_ln49_fu_610_p2 <= std_logic_vector(unsigned(zext_ln45_1_fu_584_p1) + unsigned(zext_ln1460_1_fu_592_p1));
    add_ln50_1_fu_767_p2 <= std_logic_vector(unsigned(zext_ln50_2_fu_763_p1) + unsigned(zext_ln50_1_fu_753_p1));
    add_ln50_2_fu_648_p2 <= std_logic_vector(unsigned(zext_ln48_1_fu_634_p1) + unsigned(zext_ln1460_2_fu_596_p1));
    add_ln50_3_fu_658_p2 <= std_logic_vector(unsigned(zext_ln50_4_fu_654_p1) + unsigned(zext_ln50_3_fu_644_p1));
    add_ln50_fu_757_p2 <= std_logic_vector(unsigned(zext_ln50_fu_749_p1) + unsigned(zext_ln878_fu_731_p1));
    add_ln52_1_fu_803_p2 <= std_logic_vector(unsigned(zext_ln52_3_fu_799_p1) + unsigned(zext_ln52_1_fu_785_p1));
    add_ln52_2_fu_698_p2 <= std_logic_vector(unsigned(zext_ln52_6_fu_694_p1) + unsigned(zext_ln52_4_fu_687_p1));
    add_ln52_3_fu_708_p2 <= std_logic_vector(unsigned(zext_ln52_7_fu_704_p1) + unsigned(zext_ln52_5_fu_690_p1));
    add_ln52_fu_793_p2 <= std_logic_vector(unsigned(zext_ln52_2_fu_789_p1) + unsigned(zext_ln52_fu_781_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(5);
    ap_CS_fsm_state12 <= ap_CS_fsm(6);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(gray_img_src_4207_empty_n, ap_enable_reg_pp0_iter1, icmp_ln878_reg_844)
    begin
                ap_block_pp0_stage0_11001 <= ((icmp_ln878_reg_844 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (gray_img_src_4207_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(gray_img_src_4207_empty_n, ap_enable_reg_pp0_iter1, icmp_ln878_reg_844)
    begin
                ap_block_pp0_stage0_subdone <= ((icmp_ln878_reg_844 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (gray_img_src_4207_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(gray_img_src_4207_empty_n, gaussian_mat_4209_full_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, icmp_ln870_9_reg_918_pp1_iter3_reg, ap_predicate_op89_read_state7)
    begin
                ap_block_pp1_stage0_01001 <= (((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (gaussian_mat_4209_full_n = ap_const_logic_0)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (gray_img_src_4207_empty_n = ap_const_logic_0) and (ap_predicate_op89_read_state7 = ap_const_boolean_1)));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(gray_img_src_4207_empty_n, gaussian_mat_4209_full_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, icmp_ln870_9_reg_918_pp1_iter3_reg, ap_predicate_op89_read_state7)
    begin
                ap_block_pp1_stage0_11001 <= (((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (gaussian_mat_4209_full_n = ap_const_logic_0)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (gray_img_src_4207_empty_n = ap_const_logic_0) and (ap_predicate_op89_read_state7 = ap_const_boolean_1)));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(gray_img_src_4207_empty_n, gaussian_mat_4209_full_n, ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, icmp_ln870_9_reg_918_pp1_iter3_reg, ap_predicate_op89_read_state7)
    begin
                ap_block_pp1_stage0_subdone <= (((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (gaussian_mat_4209_full_n = ap_const_logic_0)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (gray_img_src_4207_empty_n = ap_const_logic_0) and (ap_predicate_op89_read_state7 = ap_const_boolean_1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state10_pp1_stage0_iter4_assign_proc : process(gaussian_mat_4209_full_n, icmp_ln870_9_reg_918_pp1_iter3_reg)
    begin
                ap_block_state10_pp1_stage0_iter4 <= ((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (gaussian_mat_4209_full_n = ap_const_logic_0));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(gray_img_src_4207_empty_n, icmp_ln878_reg_844)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln878_reg_844 = ap_const_lv1_0) and (gray_img_src_4207_empty_n = ap_const_logic_0));
    end process;

        ap_block_state6_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp1_stage0_iter1_assign_proc : process(gray_img_src_4207_empty_n, ap_predicate_op89_read_state7)
    begin
                ap_block_state7_pp1_stage0_iter1 <= ((gray_img_src_4207_empty_n = ap_const_logic_0) and (ap_predicate_op89_read_state7 = ap_const_boolean_1));
    end process;

        ap_block_state8_pp1_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp1_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_176_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter0)
    begin
                ap_condition_176 <= ((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1));
    end process;


    ap_condition_188_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0_11001)
    begin
                ap_condition_188 <= ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_condition_732_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, bottom_load_2_reg_894)
    begin
                ap_condition_732 <= (not((bottom_load_2_reg_894 = ap_const_lv2_1)) and not((bottom_load_2_reg_894 = ap_const_lv2_0)) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln878_fu_417_p2)
    begin
        if ((icmp_ln878_fu_417_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_exit_iter3_state9_assign_proc : process(ap_enable_reg_pp1_iter3, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_1))) then 
            ap_condition_pp1_exit_iter3_state9 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter3_state9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp1_flush_enable_assign_proc : process(ap_CS_fsm_pp1_stage0, icmp_ln878_7_fu_521_p2, ap_block_pp1_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (icmp_ln878_7_fu_521_p2 = ap_const_lv1_1))) then 
            ap_condition_pp1_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp1_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln209_fu_428_p2, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter4, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter3, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0) and (ap_enable_reg_pp1_iter2 = ap_const_logic_0) and (ap_enable_reg_pp1_iter3 = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_b0_V_phi_fu_304_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, b1_V_reg_288, b0_V_reg_300, icmp_ln878_7_reg_890_pp1_iter3_reg)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
            ap_phi_mux_b0_V_phi_fu_304_p4 <= b1_V_reg_288;
        else 
            ap_phi_mux_b0_V_phi_fu_304_p4 <= b0_V_reg_300;
        end if; 
    end process;


    ap_phi_mux_b1_V_phi_fu_292_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, b1_V_reg_288, icmp_ln878_7_reg_890_pp1_iter3_reg, b2_V_reg_932)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
            ap_phi_mux_b1_V_phi_fu_292_p4 <= b2_V_reg_932;
        else 
            ap_phi_mux_b1_V_phi_fu_292_p4 <= b1_V_reg_288;
        end if; 
    end process;


    ap_phi_mux_col_V_10_phi_fu_280_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, col_V_10_reg_276, col_V_11_reg_885)
    begin
        if (((icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_col_V_10_phi_fu_280_p4 <= col_V_11_reg_885;
        else 
            ap_phi_mux_col_V_10_phi_fu_280_p4 <= col_V_10_reg_276;
        end if; 
    end process;


    ap_phi_mux_m0_V_phi_fu_329_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, m1_V_reg_313, m0_V_reg_325, icmp_ln878_7_reg_890_pp1_iter3_reg)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
            ap_phi_mux_m0_V_phi_fu_329_p4 <= m1_V_reg_313;
        else 
            ap_phi_mux_m0_V_phi_fu_329_p4 <= m0_V_reg_325;
        end if; 
    end process;

    ap_phi_mux_row_ind_V_phi_fu_268_p4 <= row_ind_V_reg_264;

    ap_phi_mux_t0_V_phi_fu_354_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, t1_V_reg_338, t0_V_reg_350, icmp_ln878_7_reg_890_pp1_iter3_reg)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
            ap_phi_mux_t0_V_phi_fu_354_p4 <= t1_V_reg_338;
        else 
            ap_phi_mux_t0_V_phi_fu_354_p4 <= t0_V_reg_350;
        end if; 
    end process;


    ap_phi_mux_t1_V_phi_fu_342_p4_assign_proc : process(ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, t1_V_reg_338, icmp_ln878_7_reg_890_pp1_iter3_reg, src_buf1_V_2_reg_922)
    begin
        if (((ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (icmp_ln878_7_reg_890_pp1_iter3_reg = ap_const_lv1_0))) then 
            ap_phi_mux_t1_V_phi_fu_342_p4 <= src_buf1_V_2_reg_922;
        else 
            ap_phi_mux_t1_V_phi_fu_342_p4 <= t1_V_reg_338;
        end if; 
    end process;

    ap_phi_reg_pp1_iter0_buf2_V_reg_375 <= "XXXXXXXX";

    ap_predicate_op89_read_state7_assign_proc : process(icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881)
    begin
                ap_predicate_op89_read_state7 <= ((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;
    bottom_2_fu_486_p3 <= 
        ap_const_lv2_1 when (icmp_ln870_fu_464_p2(0) = '1') else 
        bottom_fu_114;
    buf_V_0_address0 <= zext_ln117_fu_541_p1(11 - 1 downto 0);

    buf_V_0_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_enable_reg_pp0_iter0, zext_ln534_fu_423_p1, bottom_load_2_reg_894, zext_ln534_6_fu_527_p1, zext_ln534_5_fu_534_p1)
    begin
        if (((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0))) then 
            buf_V_0_address1 <= zext_ln534_5_fu_534_p1(11 - 1 downto 0);
        elsif (((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0))) then 
            buf_V_0_address1 <= zext_ln534_6_fu_527_p1(11 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            buf_V_0_address1 <= zext_ln534_fu_423_p1(11 - 1 downto 0);
        else 
            buf_V_0_address1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    buf_V_0_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then 
            buf_V_0_ce0 <= ap_const_logic_1;
        else 
            buf_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_block_pp1_stage0_11001, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, bottom_load_2_reg_894)
    begin
        if ((((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0)) or ((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then 
            buf_V_0_ce1 <= ap_const_logic_1;
        else 
            buf_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_0_d1_assign_proc : process(gray_img_src_4207_dout, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_enable_reg_pp0_iter0, bottom_load_2_reg_894)
    begin
        if (((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0))) then 
            buf_V_0_d1 <= gray_img_src_4207_dout;
        elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0)))) then 
            buf_V_0_d1 <= ap_const_lv8_0;
        else 
            buf_V_0_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_0_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_block_pp1_stage0_11001, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001, icmp_ln878_fu_417_p2, bottom_load_2_reg_894)
    begin
        if ((((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0)) or ((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln878_fu_417_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then 
            buf_V_0_we1 <= ap_const_logic_1;
        else 
            buf_V_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_1_address0 <= zext_ln117_fu_541_p1(11 - 1 downto 0);

    buf_V_1_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, zext_ln534_reg_848, bottom_load_2_reg_894, zext_ln534_6_fu_527_p1, zext_ln534_5_fu_534_p1)
    begin
        if (((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1))) then 
            buf_V_1_address1 <= zext_ln534_5_fu_534_p1(11 - 1 downto 0);
        elsif (((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1))) then 
            buf_V_1_address1 <= zext_ln534_6_fu_527_p1(11 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buf_V_1_address1 <= zext_ln534_reg_848(11 - 1 downto 0);
        else 
            buf_V_1_address1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    buf_V_1_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then 
            buf_V_1_ce0 <= ap_const_logic_1;
        else 
            buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001, bottom_load_2_reg_894)
    begin
        if ((((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1)) or ((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buf_V_1_ce1 <= ap_const_logic_1;
        else 
            buf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_1_d1_assign_proc : process(gray_img_src_4207_dout, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, bottom_load_2_reg_894)
    begin
        if (((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1))) then 
            buf_V_1_d1 <= ap_const_lv8_0;
        elsif ((((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            buf_V_1_d1 <= gray_img_src_4207_dout;
        else 
            buf_V_1_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_1_we1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln878_reg_844, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001, bottom_load_2_reg_894)
    begin
        if ((((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1)) or ((icmp_ln878_reg_844 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (bottom_load_2_reg_894 = ap_const_lv2_1)))) then 
            buf_V_1_we1 <= ap_const_logic_1;
        else 
            buf_V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_V_2_address0 <= zext_ln117_fu_541_p1(11 - 1 downto 0);

    buf_V_2_address1_assign_proc : process(cmp_i_i338_i_reg_881, zext_ln534_6_fu_527_p1, zext_ln534_5_fu_534_p1, ap_condition_732)
    begin
        if ((ap_const_boolean_1 = ap_condition_732)) then
            if ((cmp_i_i338_i_reg_881 = ap_const_lv1_1)) then 
                buf_V_2_address1 <= zext_ln534_5_fu_534_p1(11 - 1 downto 0);
            elsif ((cmp_i_i338_i_reg_881 = ap_const_lv1_0)) then 
                buf_V_2_address1 <= zext_ln534_6_fu_527_p1(11 - 1 downto 0);
            else 
                buf_V_2_address1 <= "XXXXXXXXXXX";
            end if;
        else 
            buf_V_2_address1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    buf_V_2_ce0_assign_proc : process(ap_block_pp1_stage0_11001, ap_enable_reg_pp1_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_enable_reg_pp1_iter2 = ap_const_logic_1))) then 
            buf_V_2_ce0 <= ap_const_logic_1;
        else 
            buf_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_2_ce1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_block_pp1_stage0_11001, bottom_load_2_reg_894)
    begin
        if (((not((bottom_load_2_reg_894 = ap_const_lv2_1)) and not((bottom_load_2_reg_894 = ap_const_lv2_0)) and (cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or (not((bottom_load_2_reg_894 = ap_const_lv2_1)) and not((bottom_load_2_reg_894 = ap_const_lv2_0)) and (cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            buf_V_2_ce1 <= ap_const_logic_1;
        else 
            buf_V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_V_2_d1_assign_proc : process(gray_img_src_4207_dout, cmp_i_i338_i_reg_881, ap_condition_732)
    begin
        if ((ap_const_boolean_1 = ap_condition_732)) then
            if ((cmp_i_i338_i_reg_881 = ap_const_lv1_1)) then 
                buf_V_2_d1 <= gray_img_src_4207_dout;
            elsif ((cmp_i_i338_i_reg_881 = ap_const_lv1_0)) then 
                buf_V_2_d1 <= ap_const_lv8_0;
            else 
                buf_V_2_d1 <= "XXXXXXXX";
            end if;
        else 
            buf_V_2_d1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_V_2_we1_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881, ap_block_pp1_stage0_11001, bottom_load_2_reg_894)
    begin
        if (((not((bottom_load_2_reg_894 = ap_const_lv2_1)) and not((bottom_load_2_reg_894 = ap_const_lv2_0)) and (cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or (not((bottom_load_2_reg_894 = ap_const_lv2_1)) and not((bottom_load_2_reg_894 = ap_const_lv2_0)) and (cmp_i_i338_i_reg_881 = ap_const_lv1_0) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            buf_V_2_we1 <= ap_const_logic_1;
        else 
            buf_V_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    cmp_i_i338_i_fu_509_p2 <= "1" when (unsigned(row_V_reg_252) < unsigned(ap_const_lv10_2D0)) else "0";
    col_V_11_fu_515_p2 <= std_logic_vector(unsigned(ap_phi_mux_col_V_10_phi_fu_280_p4) + unsigned(ap_const_lv11_1));
    col_V_9_fu_411_p2 <= std_logic_vector(unsigned(col_V_reg_241) + unsigned(ap_const_lv11_1));

    gaussian_mat_4209_blk_n_assign_proc : process(gaussian_mat_4209_full_n, ap_block_pp1_stage0, ap_enable_reg_pp1_iter4, icmp_ln870_9_reg_918_pp1_iter3_reg, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or ((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0)))) then 
            gaussian_mat_4209_blk_n <= gaussian_mat_4209_full_n;
        else 
            gaussian_mat_4209_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    gaussian_mat_4209_din_assign_proc : process(gaussian_mat_4209_full_n, ap_enable_reg_pp1_iter4, icmp_ln870_9_reg_918_pp1_iter3_reg, ap_CS_fsm_state12, g_x_V_6_reg_957, ap_block_pp1_stage0_01001, add_ln52_3_fu_708_p2)
    begin
        if (((gaussian_mat_4209_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            gaussian_mat_4209_din <= g_x_V_6_reg_957;
        elsif (((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_01001))) then 
            gaussian_mat_4209_din <= add_ln52_3_fu_708_p2(11 downto 4);
        else 
            gaussian_mat_4209_din <= "XXXXXXXX";
        end if; 
    end process;


    gaussian_mat_4209_write_assign_proc : process(gaussian_mat_4209_full_n, ap_enable_reg_pp1_iter4, icmp_ln870_9_reg_918_pp1_iter3_reg, ap_CS_fsm_state12, ap_block_pp1_stage0_11001)
    begin
        if ((((icmp_ln870_9_reg_918_pp1_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp1_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((gaussian_mat_4209_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)))) then 
            gaussian_mat_4209_write <= ap_const_logic_1;
        else 
            gaussian_mat_4209_write <= ap_const_logic_0;
        end if; 
    end process;


    gray_img_src_4207_blk_n_assign_proc : process(gray_img_src_4207_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln878_reg_844, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, icmp_ln878_7_reg_890, cmp_i_i338_i_reg_881)
    begin
        if ((((cmp_i_i338_i_reg_881 = ap_const_lv1_1) and (icmp_ln878_7_reg_890 = ap_const_lv1_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((icmp_ln878_reg_844 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            gray_img_src_4207_blk_n <= gray_img_src_4207_empty_n;
        else 
            gray_img_src_4207_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    gray_img_src_4207_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln878_reg_844, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_predicate_op89_read_state7, ap_block_pp1_stage0_11001, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_predicate_op89_read_state7 = ap_const_boolean_1)) or ((icmp_ln878_reg_844 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            gray_img_src_4207_read <= ap_const_logic_1;
        else 
            gray_img_src_4207_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln209_fu_428_p2 <= "1" when (row_V_reg_252 = ap_const_lv10_2D1) else "0";
    icmp_ln870_8_fu_825_p2 <= "1" when (row_ind_V_3_fu_819_p2 = ap_const_lv13_3) else "0";
    icmp_ln870_9_fu_548_p2 <= "1" when (col_V_10_reg_276_pp1_iter1_reg = ap_const_lv11_0) else "0";
    icmp_ln870_fu_464_p2 <= "1" when (row_ind_V_reg_264 = ap_const_lv13_1) else "0";
    icmp_ln878_7_fu_521_p2 <= "1" when (ap_phi_mux_col_V_10_phi_fu_280_p4 = ap_const_lv11_500) else "0";
    icmp_ln878_fu_417_p2 <= "1" when (col_V_reg_241 = ap_const_lv11_500) else "0";

    internal_ap_ready_assign_proc : process(icmp_ln209_fu_428_p2, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln209_fu_428_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    mid_2_fu_478_p3 <= 
        ap_const_lv2_0 when (icmp_ln870_fu_464_p2(0) = '1') else 
        mid_fu_110;
    phitmp1_fu_664_p3 <= (src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_return & ap_const_lv2_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    row_V_3_fu_725_p2 <= std_logic_vector(unsigned(row_V_reg_252) + unsigned(ap_const_lv10_1));
    row_ind_V_3_fu_819_p2 <= std_logic_vector(unsigned(row_ind_V_reg_264) + unsigned(ap_const_lv13_1));
    row_ind_V_4_fu_831_p3 <= 
        ap_const_lv13_0 when (icmp_ln870_8_fu_825_p2(0) = '1') else 
        row_ind_V_3_fu_819_p2;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tp_1_fu_470_p3 <= 
        ap_const_lv2_2 when (icmp_ln870_fu_464_p2(0) = '1') else 
        tp_fu_106;
    zext_ln117_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_10_reg_276_pp1_iter1_reg),64));
    zext_ln1460_1_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b2_V_xfExtractPixels_1_1_0_s_fu_396_ap_return),9));
    zext_ln1460_2_fu_596_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_buf2_V_2_xfExtractPixels_1_1_0_s_fu_391_ap_return),9));
    zext_ln1460_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b0_V_reg_300),9));
    zext_ln45_1_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_buf1_V_2_xfExtractPixels_1_1_0_s_fu_386_ap_return),9));
    zext_ln45_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_t0_V_phi_fu_354_p4),9));
    zext_ln46_1_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A00_fu_600_p2),10));
    zext_ln46_fu_588_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_b0_V_phi_fu_304_p4),9));
    zext_ln47_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_b1_V_phi_fu_292_p4),9));
    zext_ln48_1_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_t1_V_phi_fu_342_p4),9));
    zext_ln48_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_m0_V_phi_fu_329_p4),9));
    zext_ln49_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln49_fu_610_p2),10));
    zext_ln50_1_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(m0_V_reg_325),10));
    zext_ln50_2_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_fu_757_p2),10));
    zext_ln50_3_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln48_fu_638_p2),10));
    zext_ln50_4_fu_654_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln50_2_fu_648_p2),10));
    zext_ln50_fu_749_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t1_V_reg_338),9));
    zext_ln52_1_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A1_fu_773_p3),12));
    zext_ln52_2_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A2_reg_363),11));
    zext_ln52_3_fu_799_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_fu_793_p2),12));
    zext_ln52_4_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A0_1_reg_937),11));
    zext_ln52_5_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A1_1_fu_672_p3),12));
    zext_ln52_6_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A2_1_fu_679_p3),11));
    zext_ln52_7_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_2_fu_698_p2),12));
    zext_ln52_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(A0_fu_743_p2),11));
    zext_ln534_5_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_10_reg_276),64));
    zext_ln534_6_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_10_reg_276),64));
    zext_ln534_fu_423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_V_reg_241),64));
    zext_ln878_1_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t0_V_reg_350),9));
    zext_ln878_fu_731_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b1_V_reg_288),9));
end behav;
